---
  - name: install tomcat
    package:
      name: tomcat
      state: latest
  - name: enable tomcat at boot
    service:
      name: tomcat
      enabled: yes

  - name: create ansible tomcat directory
    file:
      path: "{{ tomcat_webroot }}"
      state: directory

  - name: copy static index.html to tomcat webroot
    template:
      src: index.html.j2
      dest: "{{ tomcat_webroot }}/index.html"
      mode: 0644
  - name: start tomcat
    service:
      name: tomcat
      state: started

