---
- name: setup repos
  hosts: all
  roles:
    - basic-config
  tags:
    - basic-config

- name: setup haproxy
  hosts: frontends
  become: yes
  roles:    
    - haproxy
  tags:
    - haproxy

- name: setup tomcat
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - tomcat
  tags:
    - tomcat

- name: setup database tier
  become: yes
  hosts: appdbs
  roles:    
    - geerlingguy.postgresql
  tags:
    - postgresql

- name: setup apache
  hosts: apps
  become: yes
  gather_facts: false
  roles:    
    - apache
  tags:
    - apache
