---
- name: setup haproxy
  hosts: frontends
  become: yes
  roles:
    - basic-config
    - haproxy

- name: setup tomcat
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - basic-config
    - tomcat

- name: setup database tier
  become: yes
  hosts: appdbs
  roles:
    - basic-config
    - geerlingguy.postgresql

- name: setup apache
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - basic-config
    - apache
