---
- name: basic config
  hosts: all
  roles:
    - {name: basic-config, tags: basic-config}
  
- name: setup haproxy
  hosts: frontends
  become: yes
  roles:    
    - {name: haproxy, tags: haproxy}

- name: setup tomcat
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - {name: tomcat, tags: tomcat}
  
- name: setup database tier
  become: yes
  hosts: appdbs
  roles:    
    - {name: geerlingguy.postgresql, tags: postgresql}
  
- name: setup apache
  hosts: apps
  become: yes
  gather_facts: false
  roles:    
    - {name: apache, tags: apache}
